{{- if .Values.auth.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teastore.auth.fullname" . }}
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.auth.svc_name }}
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "teastore.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.auth.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "teastore.auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.auth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.auth.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ include "teastore.auth.microservice" . }}
          securityContext:
            {{- toYaml .Values.auth.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_PORT
              value: {{ .Values.auth.service.port | quote }}
            - name: HOST_NAME
              value: {{ template "teastore.auth.hostname" . }}
            - name: REGISTRY_HOST
              value: {{ template "teastore.registry.url" . }}
            - name: REGISTRY_PORT
              value: {{ .Values.registry.service.port | quote }}
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
