apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.svc_name }}
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.db.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- if .Values.db.url  }}
  type: ClusterIP
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.db.service.port }}
      name: mysql-db
      targetPort: 3306
      protocol: TCP
  selector:
    {{- include "teastore.db.selectorLabels" . | nindent 4 }}
