apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.registry.svc_name }}
  labels:
    {{- include "teastore.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.registry.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- if .Values.registry.url  }}
  type: ClusterIP
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.registry.service.port }}
      name: http-registry
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "teastore.registry.selectorLabels" . | nindent 4 }}
