ARG dockerregistry=default
FROM ${dockerregistry}/petsupplystore-base:latest
MAINTAINER Chair of Software Engineering <se2-it@informatik.uni-wuerzburg.de>

COPY target/*.war /usr/local/tomcat/webapps/